// Code generated by MockGen. DO NOT EDIT.
// Source: brws/interfaces/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=brws/interfaces/interfaces.go -destination=brws/interfaces/mock_interfaces.go -package=interfaces
//

// Package interfaces is a generated GoMock package.
package interfaces

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEngine is a mock of Engine interface.
type MockEngine struct {
	ctrl     *gomock.Controller
	recorder *MockEngineMockRecorder
	isgomock struct{}
}

// MockEngineMockRecorder is the mock recorder for MockEngine.
type MockEngineMockRecorder struct {
	mock *MockEngine
}

// NewMockEngine creates a new mock instance.
func NewMockEngine(ctrl *gomock.Controller) *MockEngine {
	mock := &MockEngine{ctrl: ctrl}
	mock.recorder = &MockEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEngine) EXPECT() *MockEngineMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEngine) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockEngineMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEngine)(nil).Close))
}

// Do mocks base method.
func (m *MockEngine) Do(ctx context.Context, url string) (int, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, url)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Do indicates an expected call of Do.
func (mr *MockEngineMockRecorder) Do(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockEngine)(nil).Do), ctx, url)
}

// Name mocks base method.
func (m *MockEngine) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockEngineMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockEngine)(nil).Name))
}

// MockChallengeDetector is a mock of ChallengeDetector interface.
type MockChallengeDetector struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeDetectorMockRecorder
	isgomock struct{}
}

// MockChallengeDetectorMockRecorder is the mock recorder for MockChallengeDetector.
type MockChallengeDetectorMockRecorder struct {
	mock *MockChallengeDetector
}

// NewMockChallengeDetector creates a new mock instance.
func NewMockChallengeDetector(ctrl *gomock.Controller) *MockChallengeDetector {
	mock := &MockChallengeDetector{ctrl: ctrl}
	mock.recorder = &MockChallengeDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeDetector) EXPECT() *MockChallengeDetectorMockRecorder {
	return m.recorder
}

// Detect mocks base method.
func (m *MockChallengeDetector) Detect(body []byte) (bool, string) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detect", body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	return ret0, ret1
}

// Detect indicates an expected call of Detect.
func (mr *MockChallengeDetectorMockRecorder) Detect(body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detect", reflect.TypeOf((*MockChallengeDetector)(nil).Detect), body)
}

// MockSessionManager is a mock of SessionManager interface.
type MockSessionManager struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerMockRecorder
	isgomock struct{}
}

// MockSessionManagerMockRecorder is the mock recorder for MockSessionManager.
type MockSessionManagerMockRecorder struct {
	mock *MockSessionManager
}

// NewMockSessionManager creates a new mock instance.
func NewMockSessionManager(ctrl *gomock.Controller) *MockSessionManager {
	mock := &MockSessionManager{ctrl: ctrl}
	mock.recorder = &MockSessionManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManager) EXPECT() *MockSessionManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionManager) Create(name string) (Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name)
	ret0, _ := ret[0].(Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionManagerMockRecorder) Create(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionManager)(nil).Create), name)
}

// Delete mocks base method.
func (m *MockSessionManager) Delete(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionManagerMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionManager)(nil).Delete), id)
}

// Get mocks base method.
func (m *MockSessionManager) Get(id string) (Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", id)
	ret0, _ := ret[0].(Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionManagerMockRecorder) Get(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionManager)(nil).Get), id)
}

// List mocks base method.
func (m *MockSessionManager) List() []Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]Session)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockSessionManagerMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionManager)(nil).List))
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// ID mocks base method.
func (m *MockSession) ID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ID")
	ret0, _ := ret[0].(string)
	return ret0
}

// ID indicates an expected call of ID.
func (mr *MockSessionMockRecorder) ID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ID", reflect.TypeOf((*MockSession)(nil).ID))
}

// Name mocks base method.
func (m *MockSession) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSessionMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSession)(nil).Name))
}

// MockChallengeSolver is a mock of ChallengeSolver interface.
type MockChallengeSolver struct {
	ctrl     *gomock.Controller
	recorder *MockChallengeSolverMockRecorder
	isgomock struct{}
}

// MockChallengeSolverMockRecorder is the mock recorder for MockChallengeSolver.
type MockChallengeSolverMockRecorder struct {
	mock *MockChallengeSolver
}

// NewMockChallengeSolver creates a new mock instance.
func NewMockChallengeSolver(ctrl *gomock.Controller) *MockChallengeSolver {
	mock := &MockChallengeSolver{ctrl: ctrl}
	mock.recorder = &MockChallengeSolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengeSolver) EXPECT() *MockChallengeSolverMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockChallengeSolver) GetBalance(ctx context.Context) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockChallengeSolverMockRecorder) GetBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockChallengeSolver)(nil).GetBalance), ctx)
}

// SolveHCaptcha mocks base method.
func (m *MockChallengeSolver) SolveHCaptcha(ctx context.Context, siteKey, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SolveHCaptcha", ctx, siteKey, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SolveHCaptcha indicates an expected call of SolveHCaptcha.
func (mr *MockChallengeSolverMockRecorder) SolveHCaptcha(ctx, siteKey, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SolveHCaptcha", reflect.TypeOf((*MockChallengeSolver)(nil).SolveHCaptcha), ctx, siteKey, url)
}

// SolveRecaptchaV2 mocks base method.
func (m *MockChallengeSolver) SolveRecaptchaV2(ctx context.Context, siteKey, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SolveRecaptchaV2", ctx, siteKey, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SolveRecaptchaV2 indicates an expected call of SolveRecaptchaV2.
func (mr *MockChallengeSolverMockRecorder) SolveRecaptchaV2(ctx, siteKey, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SolveRecaptchaV2", reflect.TypeOf((*MockChallengeSolver)(nil).SolveRecaptchaV2), ctx, siteKey, url)
}

// SolveRecaptchaV3 mocks base method.
func (m *MockChallengeSolver) SolveRecaptchaV3(ctx context.Context, siteKey, url string, minScore float64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SolveRecaptchaV3", ctx, siteKey, url, minScore)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SolveRecaptchaV3 indicates an expected call of SolveRecaptchaV3.
func (mr *MockChallengeSolverMockRecorder) SolveRecaptchaV3(ctx, siteKey, url, minScore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SolveRecaptchaV3", reflect.TypeOf((*MockChallengeSolver)(nil).SolveRecaptchaV3), ctx, siteKey, url, minScore)
}

// SolveTurnstile mocks base method.
func (m *MockChallengeSolver) SolveTurnstile(ctx context.Context, siteKey, url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SolveTurnstile", ctx, siteKey, url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SolveTurnstile indicates an expected call of SolveTurnstile.
func (mr *MockChallengeSolverMockRecorder) SolveTurnstile(ctx, siteKey, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SolveTurnstile", reflect.TypeOf((*MockChallengeSolver)(nil).SolveTurnstile), ctx, siteKey, url)
}
