package lab

import (
	"encoding/json"
	"fmt"
	"math/rand"
	"net/http"
	"strings"
	"time"

	"github.com/skunkworq/stealth/brws/adversarial"
	"github.com/skunkworq/stealth/brws/behavior"
	chromiumstealth "github.com/skunkworq/stealth/brws/engine/chromium"
	"github.com/skunkworq/stealth/brws/ml/datagen"
)

// StealthConfigSnapshot mirrors datagen.StealthConfigSnapshot for unified request parsing.
// We accept both fsm_config (Python RL) and stealth_config (ml_datagen) formats.
type unifiedMLRequest struct {
	// Python RL format
	FSMConfig json.RawMessage `json:"fsm_config,omitempty"`
	// ml_datagen format
	StealthConfig *datagen.StealthConfigSnapshot `json:"stealth_config,omitempty"`
	EngineName    string                         `json:"engine_name,omitempty"`
	TargetURL     string                         `json:"target_url,omitempty"`
	FastMode      bool                           `json:"fast_mode"`
}

// handleMLEvaluateFast runs detection logic without launching a browser.
// It builds a synthetic HTTP request from the stealth config snapshot and runs
// it through the StealthDetector's AnalyzeRequest method directly.
func (s *EnhancedServer) handleMLEvaluateFast(cfg *datagen.StealthConfigSnapshot, engineName string) (*MLEvaluationResponse, error) {
	traceID := fmt.Sprintf("ml_fast_%d", time.Now().UnixNano())

	syntheticReq := buildSyntheticRequest(cfg, engineName)

	// Run through the stealth detector
	detection := s.stealthServer.AnalyzeRequest(syntheticReq, nil)

	// Extract anomalies from detection vectors
	anomalies := make([]string, 0)
	for _, vec := range detection.Vectors {
		if vec.Detected {
			anomalies = append(anomalies, vec.Indicators...)
		}
	}

	resp := &MLEvaluationResponse{
		Success:   true,
		TraceID:   traceID,
		BotScore:  detection.Score,
		IsBot:     detection.IsBot,
		Anomalies: anomalies,
		RawPayload: &adversarial.StealthDetection{
			Timestamp: detection.Timestamp,
			RequestID: detection.RequestID,
			Score:     detection.Score,
			IsBot:     detection.IsBot,
			Vectors:   detection.Vectors,
		},
	}

	// Check for captcha challenges
	allChallenges := s.stealthServer.CaptchaShield.GetActiveChallenges()
	if len(allChallenges) > 0 {
		latestChallenge := allChallenges[len(allChallenges)-1]
		resp.CaptchaPresented = true
		resp.CaptchaType = latestChallenge.Type

		solved, metrics := s.stealthServer.CaptchaShield.ValidateChallenge(latestChallenge.ID, latestChallenge.ID)
		resp.CaptchaSolved = solved
		if metrics != nil {
			resp.CaptchaSolveMs = metrics.SolveTimeMs
		}
	}

	return resp, nil
}

// buildSyntheticRequest constructs an http.Request with headers that would be
// generated by a browser with the given stealth configuration. This allows the
// StealthDetector to analyze the config without launching a real browser.
func buildSyntheticRequest(cfg *datagen.StealthConfigSnapshot, engineName string) *http.Request {
	req, _ := http.NewRequest(http.MethodGet, "http://localhost:8080/api/ml/trap", nil)

	// Set a realistic User-Agent
	if cfg.RandomUA {
		ua := chromiumstealth.UserAgents[rand.Intn(len(chromiumstealth.UserAgents))]
		req.Header.Set("User-Agent", ua)
	} else {
		// Default to a standard Chrome UA
		req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36")
	}

	// Standard browser headers
	req.Header.Set("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8")
	req.Header.Set("Accept-Language", "en-US,en;q=0.9")
	req.Header.Set("Accept-Encoding", "gzip, deflate, br")
	req.Header.Set("Connection", "keep-alive")
	req.Header.Set("Upgrade-Insecure-Requests", "1")
	req.Header.Set("Sec-Fetch-Dest", "document")
	req.Header.Set("Sec-Fetch-Mode", "navigate")
	req.Header.Set("Sec-Fetch-Site", "none")
	req.Header.Set("Sec-Fetch-User", "?1")

	// Client Hints - only if the config enables them
	if cfg.ClientHints {
		ua := req.Header.Get("User-Agent")
		version := extractChromeVersion(ua)
		req.Header.Set("Sec-Ch-Ua", fmt.Sprintf(`"Chromium";v="%s", "Google Chrome";v="%s", "Not-A.Brand";v="99"`, version, version))
		req.Header.Set("Sec-Ch-Ua-Platform", `"Windows"`)
		req.Header.Set("Sec-Ch-Ua-Mobile", "?0")
	}

	// Webdriver detection — if RemoveWebDriver is NOT set, the navigator.webdriver
	// property would be true, which we signal via a custom header for detection
	if !cfg.RemoveWebDriver {
		req.Header.Set("X-Navigator-Webdriver", "true")
	}

	// Canvas noise indicator
	if cfg.CanvasNoise {
		req.Header.Set("X-Canvas-Noise", "enabled")
	}

	// WebGL spoofing indicator
	if cfg.WebGLSpoof {
		req.Header.Set("X-WebGL-Spoof", "enabled")
	}

	// Hardware sync headers
	if cfg.HardwareSync {
		req.Header.Set("X-Hardware-Sync", "enabled")
	}
	if cfg.NetworkSync {
		req.Header.Set("X-Network-Sync", "enabled")
	}
	if cfg.PluginsSync {
		req.Header.Set("X-Plugins-Sync", "enabled")
	}
	if cfg.GeometrySync {
		req.Header.Set("X-Geometry-Sync", "enabled")
	}
	if cfg.VideoSync {
		req.Header.Set("X-Video-Sync", "enabled")
	}
	if cfg.PermissionsSync {
		req.Header.Set("X-Permissions-Sync", "enabled")
	}
	if cfg.TimezoneSync {
		req.Header.Set("X-Timezone-Sync", "enabled")
	}

	// Engine-specific characteristics
	switch strings.ToLower(engineName) {
	case "firefox":
		req.Header.Set("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0")
		req.Header.Del("Sec-Ch-Ua")
		req.Header.Del("Sec-Ch-Ua-Platform")
		req.Header.Del("Sec-Ch-Ua-Mobile")
	case "webkit":
		req.Header.Set("User-Agent", "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15")
		req.Header.Del("Sec-Ch-Ua")
		req.Header.Del("Sec-Ch-Ua-Platform")
		req.Header.Del("Sec-Ch-Ua-Mobile")
	}

	// Generate human-like behavioral data for the X-Behavioral-Data header.
	// This provides the shield's BehavioralAnalyzer with event data to analyze.
	gen := behavior.NewEventGenerator(nil)
	eventData := gen.Generate()
	if behavJSON, err := gen.ToJSON(eventData); err == nil {
		req.Header.Set("X-Behavioral-Data", behavJSON)
	}

	return req
}

// extractChromeVersion extracts the Chrome version from a User-Agent string.
func extractChromeVersion(ua string) string {
	idx := strings.Index(ua, "Chrome/")
	if idx == -1 {
		return "134"
	}
	rest := ua[idx+len("Chrome/"):]
	dotIdx := strings.Index(rest, ".")
	if dotIdx == -1 {
		return "134"
	}
	return rest[:dotIdx]
}

// snapshotFromFSMConfig converts the Python RL fsm_config JSON to a StealthConfigSnapshot.
func snapshotFromFSMConfig(raw json.RawMessage) (*datagen.StealthConfigSnapshot, error) {
	// The Python RL sends PascalCase keys matching stealth.StealthConfig
	var fsmCfg struct {
		Enabled             bool    `json:"Enabled"`
		RemoveWebDriver     bool    `json:"RemoveWebDriver"`
		CanvasNoise         bool    `json:"CanvasNoise"`
		ClientHints         bool    `json:"ClientHints"`
		RandomUserAgent     bool    `json:"RandomUserAgent"`
		WebGLSpoof          bool    `json:"WebGLSpoof"`
		HardwareSync        bool    `json:"HardwareSync"`
		NetworkSync         bool    `json:"NetworkSync"`
		PluginsSync         bool    `json:"PluginsSync"`
		GeometrySync        bool    `json:"GeometrySync"`
		VideoSync           bool    `json:"VideoSync"`
		PermissionsSync     bool    `json:"PermissionsSync"`
		TimezoneSync        bool    `json:"TimezoneSync"`
		CanvasNoiseStrength float64 `json:"CanvasNoiseStrength"`
	}
	if err := json.Unmarshal(raw, &fsmCfg); err != nil {
		return nil, fmt.Errorf("decode fsm_config: %w", err)
	}
	return &datagen.StealthConfigSnapshot{
		RemoveWebDriver: fsmCfg.RemoveWebDriver,
		CanvasNoise:     fsmCfg.CanvasNoise,
		ClientHints:     fsmCfg.ClientHints,
		RandomUA:        fsmCfg.RandomUserAgent,
		WebGLSpoof:      fsmCfg.WebGLSpoof,
		HardwareSync:    fsmCfg.HardwareSync,
		NetworkSync:     fsmCfg.NetworkSync,
		PluginsSync:     fsmCfg.PluginsSync,
		GeometrySync:    fsmCfg.GeometrySync,
		VideoSync:       fsmCfg.VideoSync,
		PermissionsSync: fsmCfg.PermissionsSync,
		TimezoneSync:    fsmCfg.TimezoneSync,
		CanvasNoiseStr:  fsmCfg.CanvasNoiseStrength,
	}, nil
}
